sudo: required
dist: trusty

language: cpp

compiler:
  - gcc

script: ./tests.sh

before_install:
  - chmod 755 tests.sh
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo add-apt-repository ppa:ubuntu-sdk-team/ppa -y
  - sudo apt-get update -qq
  - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.9; fi
  - if [ "$CXX" = "g++" ]; then sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.9 90; fi
  - sudo apt-get install libgtest-dev
  - sudo apt-get install google-mock
  - sudo apt-get install -qq qt5-qmake qtbase5-dev qt5-default qttools5-dev-tools
  - sudo apt-get update
  - sudo apt-get install libboost1.55-dev
  - chmod 755 ci/build_gtest.sh
  - sudo ci/build_gtest.sh
  - chmod 755 ci/build_etl.sh
  - sudo ci/build_etl.sh
#  - wget http://ftp.de.debian.org/debian/pool/main/l/lcov/lcov_1.11.orig.tar.gz
#  - tar xf lcov_1.11.orig.tar.gz
  - wget http://ftp.de.debian.org/debian/pool/main/l/lcov/lcov_1.9.orig.tar.gz
  - tar xf lcov_1.9.orig.tar.gz
  - sudo make -C lcov-1.9/ install
  # install lcov to coveralls conversion + upload tool
#  - gem install coveralls-lcov
  - pip install --user cpp-coveralls

after_success:
#  - lcov --list app.info # debug before upload
#  - coveralls-lcov app.info # uploads
#  - ls -lrth
  - cat app.info
#  - cat lcov.log
#  - cat lcov.err
  - coveralls --exclude tests --gcov-options '\-lp'
