sudo: required
dist: trusty

language: cpp

compiler:
  - gcc

script: ./tests.sh

before_install:
  - chmod 755 tests.sh
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo add-apt-repository ppa:ubuntu-sdk-team/ppa -y
  - sudo apt-get update -qq
#  - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.9; fi
#  - if [ "$CXX" = "g++" ]; then sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.9 90; fi
  - sudo apt-get install libgtest-dev
  - sudo apt-get install google-mock
  - sudo apt-get install -qq qt5-qmake qtbase5-dev qt5-default qttools5-dev-tools
  - sudo apt-get update
  - sudo apt-get install libboost1.55-dev
  - chmod 755 ci/build_gtest.sh
  - sudo ci/build_gtest.sh
  - chmod 755 ci/build_etl.sh
  - sudo ci/build_etl.sh
  - pip install --user cpp-coveralls

after_success:
  - cpp-coveralls --exclude externals --include common --include tests --gcov-options '\-lp' --verbose
